# Dependencies
markdown:         kramdown
highlighter: null

# Permalinks
permalink:        pretty

# Setup
title:            Fábio Sales
tagline:          'A Web Developer from Brasil.'
description:      ''
url:              https://ffabiosales.github.io

author:
  name:           'Fábio Sales'
  url:            https://ffabiosales.github.io

paginate:         5

# Custom vars
