# Dependencies
markdown:         kramdown
highlighter: null

# Permalinks
permalink:        pretty

# Setup
title:            Fábio Sales
tagline:          'A Web Developer from Brasil.'
description:      ''
url:              http://fabiosales.com

author:
  name:           'Fábio Sales'
  url:            http://fabiosales.com

paginate:         5

# Custom vars